services:
  - type: web
    name: vpricingapp
    runtime: python
    plan: free
    region: singapore
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn vpricing_app.main:app --app-dir src --host 0.0.0.0 --port $PORT
    healthCheckPath: /api/health
